{"currency":[
	{"short":"AED","long":"United Arab Emirates Dirham"},
	{"short":"AFN","long":"Afghanistan Afghani"},
	{"short":"ALL","long":"Albania Lek"},
	{"short":"AMD","long":"Armenia Dram"},
	{"short":"ANG","long":"Netherlands Antilles Guilder"},
	{"short":"AOA","long":"Angola Kwanza"},
	{"short":"ARS","long":"Argentina Peso"},
	{"short":"AUD","long":"Australia Dollar"},
	{"short":"AWG","long":"Aruba Guilder"},
	{"short":"AZN","long":"Azerbaijan New Manat"},
	{"short":"BAM","long":"Bosnia and Herzegovina Convertible Marka"},
	{"short":"BBD","long":"Barbados Dollar"},
	{"short":"BDT","long":"Bangladesh Taka"},
	{"short":"BGN","long":"Bulgaria Lev"},
	{"short":"BHD","long":"Bahrain Dinar"},
	{"short":"BIF","long":"Burundi Franc"},
	{"short":"BMD","long":"Bermuda Dollar"},
	{"short":"BND","long":"Brunei Darussalam Dollar"},
	{"short":"BOB","long":"Bolivia Boliviano"},
	{"short":"BRL","long":"Brazil Real"},
	{"short":"BSD","long":"Bahamas Dollar"},
	{"short":"BTN","long":"Bhutan Ngultrum"},
	{"short":"BWP","long":"Botswana Pula"},
	{"short":"BYR","long":"Belarus Ruble"},
	{"short":"BZD","long":"Belize Dollar"},
	{"short":"CAD","long":"Canada Dollar"},
	{"short":"CDF","long":"Congo/Kinshasa Franc"},
	{"short":"CHF","long":"Switzerland Franc"},
	{"short":"CLP","long":"Chile Peso"},
	{"short":"CNY","long":"China Yuan Renminbi"},
	{"short":"COP","long":"Colombia Peso"},
	{"short":"CRC","long":"Costa Rica Colon"},
	{"short":"CUC","long":"Cuba Convertible Peso"},
	{"short":"CUP","long":"Cuba Peso"},
	{"short":"CVE","long":"Cape Verde Escudo"},
	{"short":"CZK","long":"Czech Republic Koruna"},
	{"short":"DJF","long":"Djibouti Franc"},
	{"short":"DKK","long":"Denmark Krone"},
	{"short":"DOP","long":"Dominican Republic Peso"},
	{"short":"DZD","long":"Algeria Dinar"},
	{"short":"EGP","long":"Egypt Pound"},
	{"short":"ERN","long":"Eritrea Nakfa"},
	{"short":"ETB","long":"Ethiopia Birr"},
	{"short":"EUR","long":"Euro Member Countries"},
	{"short":"FJD","long":"Fiji Dollar"},
	{"short":"FKP","long":"Falkland Islands (Malvinas) Pound"},
	{"short":"GBP","long":"United Kingdom Pound"},
	{"short":"GEL","long":"Georgia Lari"},
	{"short":"GGP","long":"Guernsey Pound"},
	{"short":"GHS","long":"Ghana Cedi"},
	{"short":"GIP","long":"Gibraltar Pound"},
	{"short":"GMD","long":"Gambia Dalasi"},
	{"short":"GNF","long":"Guinea Franc"},
	{"short":"GTQ","long":"Guatemala Quetzal"},
	{"short":"GYD","long":"Guyana Dollar"},
	{"short":"HKD","long":"Hong Kong Dollar"},
	{"short":"HNL","long":"Honduras Lempira"},
	{"short":"HRK","long":"Croatia Kuna"},
	{"short":"HTG","long":"Haiti Gourde"},
	{"short":"HUF","long":"Hungary Forint"},
	{"short":"IDR","long":"Indonesia Rupiah"},
	{"short":"ILS","long":"Israel Shekel"},
	{"short":"IMP","long":"Isle of Man Pound"},
	{"short":"INR","long":"India Rupee"},
	{"short":"IQD","long":"Iraq Dinar"},
	{"short":"IRR","long":"Iran Rial"},
	{"short":"ISK","long":"Iceland Krona"},
	{"short":"JEP","long":"Jersey Pound"},
	{"short":"JMD","long":"Jamaica Dollar"},
	{"short":"JOD","long":"Jordan Dinar"},
	{"short":"JPY","long":"Japan Yen"},
	{"short":"KES","long":"Kenya Shilling"},
	{"short":"KGS","long":"Kyrgyzstan Som"},
	{"short":"KHR","long":"Cambodia Riel"},
	{"short":"KMF","long":"Comoros Franc"},
	{"short":"KPW","long":"Korea (North) Won"},
	{"short":"KRW","long":"Korea (South) Won"},
	{"short":"KWD","long":"Kuwait Dinar"},
	{"short":"KYD","long":"Cayman Islands Dollar"},
	{"short":"KZT","long":"Kazakhstan Tenge"},
	{"short":"LAK","long":"Laos Kip"},
	{"short":"LBP","long":"Lebanon Pound"},
	{"short":"LKR","long":"Sri Lanka Rupee"},
	{"short":"LRD","long":"Liberia Dollar"},
	{"short":"LSL","long":"Lesotho Loti"},
	{"short":"LYD","long":"Libya Dinar"},
	{"short":"MAD","long":"Morocco Dirham"},
	{"short":"MDL","long":"Moldova Leu"},
	{"short":"MGA","long":"Madagascar Ariary"},
	{"short":"MKD","long":"Macedonia Denar"},
	{"short":"MMK","long":"Myanmar (Burma) Kyat"},
	{"short":"MNT","long":"Mongolia Tughrik"},
	{"short":"MOP","long":"Macau Pataca"},
	{"short":"MRO","long":"Mauritania Ouguiya"},
	{"short":"MUR","long":"Mauritius Rupee"},
	{"short":"MVR","long":"Maldives (Maldive Islands) Rufiyaa"},
	{"short":"MWK","long":"Malawi Kwacha"},
	{"short":"MXN","long":"Mexico Peso"},
	{"short":"MYR","long":"Malaysia Ringgit"},
	{"short":"MZN","long":"Mozambique Metical"},
	{"short":"NAD","long":"Namibia Dollar"},
	{"short":"NGN","long":"Nigeria Naira"},
	{"short":"NIO","long":"Nicaragua Cordoba"},
	{"short":"NOK","long":"Norway Krone"},
	{"short":"NPR","long":"Nepal Rupee"},
	{"short":"NZD","long":"New Zealand Dollar"},
	{"short":"OMR","long":"Oman Rial"},
	{"short":"PAB","long":"Panama Balboa"},
	{"short":"PEN","long":"Peru Nuevo Sol"},
	{"short":"PGK","long":"Papua New Guinea Kina"},
	{"short":"PHP","long":"Philippines Peso"},
	{"short":"PKR","long":"Pakistan Rupee"},
	{"short":"PLN","long":"Poland Zloty"},
	{"short":"PYG","long":"Paraguay Guarani"},
	{"short":"QAR","long":"Qatar Riyal"},
	{"short":"RON","long":"Romania New Leu"},
	{"short":"RSD","long":"Serbia Dinar"},
	{"short":"RUB","long":"Russia Ruble"},
	{"short":"RWF","long":"Rwanda Franc"},
	{"short":"SAR","long":"Saudi Arabia Riyal"},
	{"short":"SBD","long":"Solomon Islands Dollar"},
	{"short":"SCR","long":"Seychelles Rupee"},
	{"short":"SDG","long":"Sudan Pound"},
	{"short":"SEK","long":"Sweden Krona"},
	{"short":"SGD","long":"Singapore Dollar"},
	{"short":"SHP","long":"Saint Helena Pound"},
	{"short":"SLL","long":"Sierra Leone Leone"},
	{"short":"SOS","long":"Somalia Shilling"},
	{"short":"SPL","long":"Seborga Luigino"},
	{"short":"SRD","long":"Suriname Dollar"},
	{"short":"STD","long":"São Tomé and Príncipe Dobra"},
	{"short":"SVC","long":"El Salvador Colon"},
	{"short":"SYP","long":"Syria Pound"},
	{"short":"SZL","long":"Swaziland Lilangeni"},
	{"short":"THB","long":"Thailand Baht"},
	{"short":"TJS","long":"Tajikistan Somoni"},
	{"short":"TMT","long":"Turkmenistan Manat"},
	{"short":"TND","long":"Tunisia Dinar"},
	{"short":"TOP","long":"Tonga Pa'anga"},
	{"short":"TRY","long":"Turkey Lira"},
	{"short":"TTD","long":"Trinidad and Tobago Dollar"},
	{"short":"TVD","long":"Tuvalu Dollar"},
	{"short":"TWD","long":"Taiwan New Dollar"},
	{"short":"TZS","long":"Tanzania Shilling"},
	{"short":"UAH","long":"Ukraine Hryvnia"},
	{"short":"UGX","long":"Uganda Shilling"},
	{"short":"USD","long":"United States Dollar"},
	{"short":"UYU","long":"Uruguay Peso"},
	{"short":"UZS","long":"Uzbekistan Som"},
	{"short":"VEF","long":"Venezuela Bolivar"},
	{"short":"VND","long":"Viet Nam Dong"},
	{"short":"VUV","long":"Vanuatu Vatu"},
	{"short":"WST","long":"Samoa Tala"},
	{"short":"XAF","long":"Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
	{"short":"XCD","long":"East Caribbean Dollar"},
	{"short":"XDR","long":"International Monetary Fund (IMF) Special Drawing Rights"},
	{"short":"XOF","long":"Communauté Financière Africaine (BCEAO) Franc"},
	{"short":"XPF","long":"Comptoirs Français du Pacifique (CFP) Franc"},
	{"short":"YER","long":"Yemen Rial"},
	{"short":"ZAR","long":"South Africa Rand"},
	{"short":"ZMW","long":"Zambia Kwacha"},
	{"short":"ZWD","long":"Zimbabwe Dollar"}
]
}